In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('./data/processed/202311292041/property_amenities.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84617 entries, 0 to 84616
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   property_id   84617 non-null  int64
 1   amenity_type  84617 non-null  object
 2   amenity_name  84617 non-null  object
 3   latitude      84617 non-null  float64
 4   longitude     84617 non-null  float64
 5   distance_km   84617 non-null  float64
dtypes: float64(3), int64(1), object(2)
memory usage: 3.9+ MB

In [7]:
temp = data.groupby(by=['property_id', 'amenity_type','amenity_name','latitude','longitude'])['distance_km'].count().reset_index()

temp[temp['distance_km']>1]

,property_id,amenity_type,amenity_name,latitude,longitude,distance_km
59,20090682,cycling_path,Clementi,1.316440,103.765047,2
61,20090682,cycling_path,Clementi,1.317859,103.765901,2
63,20090682,cycling_path,Clementi,1.318470,103.765855,2
65,20090682,cycling_path,Clementi,1.318711,103.765919,2
67,20090682,cycling_path,Clementi,1.319475,103.766245,2
...,...,...,...,...,...,...
82524,24841369,cycling_path,Bedok,1.331041,103.925755,2
82540,24841369,cycling_path,Bedok,1.331630,103.930464,2
83052,24841373,cycling_path,Bedok,1.322973,103.923367,2
83096,24841373,cycling_path,Bedok,1.326919,103.925421,2
83153,24841373,cycling_path,Bedok,1.331041,103.925755,2

In [8]:
data[(data['property_id']==20090682)&(data['amenity_type']=='cycling_path')&(data['amenity_name']=='Clementi')]

,property_id,amenity_type,amenity_name,latitude,longitude,distance_km
54937,20090682,cycling_path,Clementi,1.316440,103.765047,1.969151
54938,20090682,cycling_path,Clementi,1.316440,103.765047,1.969151
54939,20090682,cycling_path,Clementi,1.317859,103.765901,2.132542
54940,20090682,cycling_path,Clementi,1.317859,103.765901,2.132542
54941,20090682,cycling_path,Clementi,1.318470,103.765855,2.199364
54942,20090682,cycling_path,Clementi,1.318470,103.765855,2.199364
54943,20090682,cycling_path,Clementi,1.318711,103.765919,2.226633
54944,20090682,cycling_path,Clementi,1.318711,103.765919,2.226633
54945,20090682,cycling_path,Clementi,1.320501,103.767219,2.440045
54946,20090682,cycling_path,Clementi,1.319475,103.766245,2.314169
54947,20090682,cycling_path,Clementi,1.319475,103.766245,2.314169
54948,20090682,cycling_path,Clementi,1.320330,103.767056,2.418744
54949,20090682,cycling_path,Clementi,1.320330,103.767056,2.418744
54950,20090682,cycling_path,Clementi,1.320682,103.767395,2.462642
54951,20090682,cycling_path,Clementi,1.317852,103.765965,2.132516
54956,20090682,cycling_path,Clementi,1.311727,103.779067,2.204145
54957,20090682,cycling_path,Clementi,1.318624,103.765908,2.216945
54958,20090682,cycling_path,Clementi,1.319417,103.766196,2.307273
54959,20090682,cycling_path,Clementi,1.320266,103.767001,2.410951
54960,20090682,cycling_path,Clementi,1.320859,103.767566,2.484865
54961,20090682,cycling_path,Clementi,1.320916,103.767632,2.492235
54962,20090682,cycling_path,Clementi,1.320682,103.767395,2.462642
54963,20090682,cycling_path,Clementi,1.318113,103.765898,2.160516
54964,20090682,cycling_path,Clementi,1.304763,103.764888,0.680633